name: 'Deploy to Heroku'
description: 'Deploy a docker image to Heroku'
author: 'Runn'
inputs:
  heroku_api_key:
    description: "This will be used for authentication. You can find it in your heroku homepage account settings"
    required: true
  heroku_email:
    description: "Email that you use with heroku"
    required: true
  images:
    description: "Comma separated list of images to deploy"
    required: true
runs:
  using: 'node12'
  main: 'bin/index.js'
