name: 'Deploy to Heroku'
description: 'Deploy a docker image to Heroku'
author: 'Runn'
inputs:
  github_api_key:
    description: "This will be used to check the status of pull requests."
    required: true
  heroku_api_key:
    description: "This will be used for authentication. You can find it in your heroku homepage account settings"
    required: true
  heroku_email:
    description: "Email that you use with heroku"
    required: true
  hasura_admin_secret:
    description: "The password to set for the Hasura Admin console."
    required: true
  images:
    description: "Comma separated list of images to deploy. Each image should be of the form `appType_processType`"
    required: true
runs:
  using: 'node12'
  main: 'bin/index.js'
